### ISSUE TITLE
Congrats and one question

### ISSUE THREAD

**Issue by guiocavalcanti** [bobvanluijt/Logical-escaped_fragment#1]
Hey @kubrickology, I was doing an SEO experiment to test exactly your approach but found your repository. I was aware Google executes JavaScripts fired `onload` but I wasn't sure if the same applied to URLs with `_escaped_fragment_`. Congratulations you saved me lot of time.

That said, I need to know if you have an actual example of this technique working into the wild. 

![](http://media.giphy.com/media/92wsX8GEoNTYA/giphy.gif)

**Comment by bobvanluijt** [comment]
Hi @guiocavalcanti ,
Thanks, nice, like the beer :-P

In the README.MD you can see the screenshots, or, if you download the complete repo and use Google's "Fetch as Googlebot". You can see it working too: https://www.google.com/webmasters/tools/googlebot-fetch

**Comment by guiocavalcanti** [comment]
@kubrickology I'm sorry, I think I made the wrong question. I'd like to see if Google followed the links with `#!` in your page. For example, searching for `site:kubrickolo.gy/SEO-AJAX-example/url1.html` returns no results.

**Comment by bobvanluijt** [comment]
That's because they are not being submitted to Google, changed this though because you're the 2nd one to ask ;-)

However, if you would use the above, you can check it directly and you don't have to wait for the Google Bot.
